vg-mjg/mjg-repo

- index.html
> Tourney update

- index.html
> Trash event

- index.html
> Remove tourney

- tourneys.html
Looks like I didn't destroy anything in the process
> Added the repo of the Fortune Tourney Tool

- index.html
> fixed broken Minhou link in repo front page

- others/vn.html
ryuublogger changed to ryuugames
> fixed dead link

- guides/newfren-readme.html
> fixed link and description of Himejanki

- index.html
If it break the repository, then please roll this back.
> (testing) Coundown Timer

- library.html
Transferred to others because it also reviews Majsoul logs. Also renamed to Akochan Reviewer.
The repository code is such a mess that I'll apologize in advance if I break something.
> Transfered Tenhou log analyzer

- index.html
Added the batch file in the announcement portion.
> Added akochan batch file

- library.html
Added the ep 7 and 8 **subs** for the Zugan anime
> Added the ep 7 and 8 for the Zugan anime

- index.html
- js/index.js
Working on it this weekend (except if @Furitenman do something before me)
#51 
Not sure how this work, but I don't have time for now to make a true fix
Looks like when the theme was light before in local storage, that meant dark theme...
> Shitty fix for the dark and light mode bug

- index.html
- js/index.js
> Revert "Shitty fix for the dark and light mode bug"

- darkie.js
- js/index.js
> Fix for the dark light mode theme V2

- library.html
I hope I didn't fuck up. I'm not good with computer.
> Add FriendlyMatchPlus mod to the library

- css/dark.css
- css/light.css
- guides/newfren-readme.html
- js/library.js
- library.html
Same deal as the rest. There was a lot of code to clean, specially dead tags and empty spaces. Now it should be a lot easier to add/modify/delete content.
[Dark theme](https://user-images.githubusercontent.com/82289213/116105408-968a4b80-a6b1-11eb-95b4-2ea58a3da59b.png)
[Light theme](https://user-images.githubusercontent.com/82289213/116105485-a7d35800-a6b1-11eb-9b9a-681e99c52672.png)
> Revamp library.html

- css/dark.css
- css/light.css
As mentioned in the issue #61 there was a bug in the menu, this fixes it.
> Fix of issue with menu

- library.html
> Revert "Fixed id links"

- index.html
- js/library.js
- library.html
Title says it all. My fault for not testing thoroughly the library.html before doing the PR.
> Fix bug with library anchors from issue #66

- index.html
> Fixed fall league signup deadline

- resources/resources-strategy.html
- updates.json
Updated sms with chapter 2 translated, added new entry to the updates feed
> SMS updated

- resources/resources-majplus.html
- updates.json
Added the two new halloween emotes (Kana and Ren)
also fixed literally who's halloween emote cos it was broken and i haven't seen it at all for the last year to confirm it
> high quality emote mod update

- index.html
I can't believe you fags killed my teammate, apologise to him now.
Also I can't use files.riichi.moe so I just stuck it on catbox, you fix it.
> Change Loli of the week to Oppai of the week

- library.html
But with the library this time
> Same shit as before

- README.md
> removed schizo emails

- updates.json
I can't believe my permissions to push directly got removed
> M-League fantasy league

- resources/resources-strategy.html
The book can be found here: https://files.riichi.moe/pr/books%20(en)/100%20Latest%20Techniques%20of%20Strong%20Players%20-%20Hidehito%20Higa.pdf and in the commit, the /pr/ has been replaced with /mjg/
> Update resources-strategy.html to include Higa Hidehito's 100 WWYD book

- resources/resources-offline.html
> new hentai game

- resources/resources-gguides.html
- resources/resources-strategy.html
files for wwyd4 and TO guide have been uploaded to /pr/ please copy to /mjg/
> adding link and desc for wwyd4 and TO guide

- tourneys.html
Let me know in the IRC I got any information wrong or if I fucked this up somehow
Thanks
> Add the 16th /V/idya Riichi Mahjong Tournament to the Tourneys page

- 404.html
What it says on the tin, basically.
> When auto-update is enabled, add an unread post notif to the doc title.

- 404.html
This is roughly the same functionality as the userscript.
It also probably does not play nicely with the userscript, so I'll leave it for someone else to merge.
> Add post previews on reference hovering.

- 404.html
> Spoiler links

- 404.html
Someone in /dev/ wanted the number of unread posts to be dynamic as you scroll by
> Replace scroll listener with `IntersectionObserver`

- others/userscripts/4chan/FC2 Emote Replacer.user.js
- others/userscripts/4chan/mjg Emote Replacer.user.js
- others/userscripts/4chan/mjg Repochan Theme.user.js
- others/userscripts/4chan/mjg Tiler.user.js
- others/userstyles/4chan Repochan theme.css
- resources/resources-mjg.html
Please review resources/resources-mjg.html and check that I didn't bungle it up, as this is my first contribution to the repo and am doing all of this blindly from the web interface.
Apologies if I did.
> Upload userscripts and userstyles contributed by various Anons and add links to them.

- others/userscripts/4chan/mjg Emote Replacer.user.js
Modified the emote replacer userscript to include RC emotes normalized and hosted on files.riichi.moe.
Maybe someone could move the emotes from [files.riichi.moe/pr](https://files.riichi.moe/pr/) to [files.riichi.moe/mjg](https://files.riichi.moe/mjg/) since I don't know how that works.
> Modified the emote replacer userscript to include RC emotes

- others/userscripts/4chan/mjg Emote Replacer.user.js
no one merged the emotes folder to [files.riichi.moe/mjg](https://files.riichi.moe/mjg/) moegiharaaoi-5.gif
> Switching source for RC emotes

- others/userscripts/4chan/mjg Emote Replacer.user.js
- Reworked the emote URL existence check to optimize the amount of requests sent
- Reverted RC emote loading location to a folder located on files.riichi.moe and removed dependency on third party website (please upload new RC emotes somewhere and ask repomeidos to upload them to files.riichi.moe)
- Removed custom emote loading (do not trust user uploads to avoid daily dose-like incidents :^))
- Code refactor
> Rework URL checking logic and disable loading user-uploaded content
